trigger:
- none

pool:
  name: default

resources:
  webhooks:
    - webhook: newHarborImage
      connection: newHarborImageSC

stages:

- stage: Deploy_To_Dev
  jobs:
  - job: Deploy_To_Dev
    steps:
    - script: |
        echo 'Deploy To Dev.......'