trigger:
- main

variables:
- group: global parameters

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python $(pythonVersion)'
      inputs:
        versionSpec: '$(pythonVersion)'

    - script: 'pip install -r requirements.txt'
      displayName: 'Install Dependencies'

    - task: ArchiveFiles@2
      displayName: 'Archive '
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory) '

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        ArtifactName: flask

- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    pool:
      name: shak-agent
      demands:
      - agent.name -equals windows_server
      
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Pipeline Artifact'
      inputs:
        artifactName: flask
        targetPath: 'C:\agent\_work\deploy'
 
    - task: ExtractFiles@1
      displayName: 'Extract files '
      inputs:
        destinationFolder: 'C:\agent\_work\deploy'

    - script: 'C:\agent\_work\_tool\Python\3.9\x64\python.exe C:\agent\_work\deploy\app.py'
      displayName: 'Command Line Script'