apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-app
  name: nginx-app
  namespace: app-test
spec:
  containers:
  - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    name: nginx-app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
